# Generated by Django 3.1.6 on 2021-02-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrant',
            name='group',
        ),
        migrations.AlterField(
            model_name='temperature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_temperatures', to='core.entrant'),
        ),
    ]
